# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'delwin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Del(object):
    def setupUi(self, Form_Del):
        Form_Del.setObjectName("Form_Del")
        Form_Del.resize(401, 252)
        self.widget = QtWidgets.QWidget(Form_Del)
        self.widget.setGeometry(QtCore.QRect(50, 50, 299, 138))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lab_delTest = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_delTest.setFont(font)
        self.lab_delTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_delTest.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_delTest.setObjectName("lab_delTest")
        self.verticalLayout_2.addWidget(self.lab_delTest)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lab_selecCalss = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_selecCalss.setFont(font)
        self.lab_selecCalss.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_selecCalss.setObjectName("lab_selecCalss")
        self.horizontalLayout_2.addWidget(self.lab_selecCalss)
        self.comboBox_selectClass = QtWidgets.QComboBox(self.widget)
        self.comboBox_selectClass.setObjectName("comboBox_selectClass")
        self.horizontalLayout_2.addWidget(self.comboBox_selectClass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lab_selecLable = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_selecLable.setFont(font)
        self.lab_selecLable.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lab_selecLable.setObjectName("lab_selecLable")
        self.horizontalLayout_3.addWidget(self.lab_selecLable)
        self.comboBox_selectId = QtWidgets.QComboBox(self.widget)
        self.comboBox_selectId.setObjectName("comboBox_selectId")
        self.horizontalLayout_3.addWidget(self.comboBox_selectId)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.btn_Refresh = QtWidgets.QPushButton(self.widget)
        self.btn_Refresh.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Refresh.setFont(font)
        self.btn_Refresh.setObjectName("btn_Refresh")
        self.horizontalLayout_4.addWidget(self.btn_Refresh)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_Enter = QtWidgets.QPushButton(self.widget)
        self.btn_Enter.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Enter.setFont(font)
        self.btn_Enter.setObjectName("btn_Enter")
        self.horizontalLayout.addWidget(self.btn_Enter)
        self.btn_Cancel = QtWidgets.QPushButton(self.widget)
        self.btn_Cancel.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Cancel.setFont(font)
        self.btn_Cancel.setObjectName("btn_Cancel")
        self.horizontalLayout.addWidget(self.btn_Cancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form_Del)
        QtCore.QMetaObject.connectSlotsByName(Form_Del)

    def retranslateUi(self, Form_Del):
        _translate = QtCore.QCoreApplication.translate
        Form_Del.setWindowTitle(_translate("Form_Del", "Form"))
        self.lab_delTest.setText(_translate("Form_Del", "选择需要删除的班级学号"))
        self.lab_selecCalss.setText(_translate("Form_Del", "选择班级"))
        self.lab_selecLable.setText(_translate("Form_Del", "选择学号"))
        self.btn_Refresh.setText(_translate("Form_Del", "查询"))
        self.btn_Enter.setText(_translate("Form_Del", "确定"))
        self.btn_Cancel.setText(_translate("Form_Del", "取消"))

