# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sqlite_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SqliteMainWindow(object):
    def setupUi(self, SqliteMainWindow):
        SqliteMainWindow.setObjectName("SqliteMainWindow")
        SqliteMainWindow.resize(920, 674)
        self.centralwidget = QtWidgets.QWidget(SqliteMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 540, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 550, 431, 26))
        self.lineEdit.setObjectName("lineEdit")
        self.tableView_content = QtWidgets.QTableView(self.centralwidget)
        self.tableView_content.setGeometry(QtCore.QRect(430, 80, 381, 421))
        self.tableView_content.setObjectName("tableView_content")
        self.groupBox_table_field = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_table_field.setGeometry(QtCore.QRect(50, 60, 371, 451))
        self.groupBox_table_field.setObjectName("groupBox_table_field")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_table_field)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 341, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_table = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_table.setFont(font)
        self.label_table.setAlignment(QtCore.Qt.AlignCenter)
        self.label_table.setObjectName("label_table")
        self.verticalLayout_4.addWidget(self.label_table)
        self.scrollArea_table = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea_table.setWidgetResizable(True)
        self.scrollArea_table.setObjectName("scrollArea_table")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 163, 357))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_table.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea_table)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_field = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_field.setFont(font)
        self.label_field.setAlignment(QtCore.Qt.AlignCenter)
        self.label_field.setObjectName("label_field")
        self.verticalLayout_3.addWidget(self.label_field)
        self.scrollArea_field = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea_field.setWidgetResizable(True)
        self.scrollArea_field.setObjectName("scrollArea_field")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 162, 319))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea_field.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_field)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(830, 20, 84, 94))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_del = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_del.setObjectName("pushButton_del")
        self.verticalLayout.addWidget(self.pushButton_del)
        self.pushButton_add = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_add.setObjectName("pushButton_add")
        self.verticalLayout.addWidget(self.pushButton_add)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton_query = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_query.setObjectName("pushButton_query")
        self.verticalLayout_2.addWidget(self.pushButton_query)
        SqliteMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SqliteMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SqliteMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SqliteMainWindow)
        self.statusbar.setObjectName("statusbar")
        SqliteMainWindow.setStatusBar(self.statusbar)
        self.actionOpen_File = QtWidgets.QAction(SqliteMainWindow)
        self.actionOpen_File.setObjectName("actionOpen_File")
        self.menuFile.addAction(self.actionOpen_File)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SqliteMainWindow)
        QtCore.QMetaObject.connectSlotsByName(SqliteMainWindow)

    def retranslateUi(self, SqliteMainWindow):
        _translate = QtCore.QCoreApplication.translate
        SqliteMainWindow.setWindowTitle(_translate("SqliteMainWindow", "Sqlite Main Window"))
        self.label.setText(_translate("SqliteMainWindow", "命令"))
        self.groupBox_table_field.setTitle(_translate("SqliteMainWindow", "选择一个表和若干字段"))
        self.label_table.setText(_translate("SqliteMainWindow", "表"))
        self.label_field.setText(_translate("SqliteMainWindow", "字段"))
        self.radioButton_2.setText(_translate("SqliteMainWindow", "全不选"))
        self.radioButton.setText(_translate("SqliteMainWindow", "全选"))
        self.pushButton_del.setText(_translate("SqliteMainWindow", "删除"))
        self.pushButton_add.setText(_translate("SqliteMainWindow", "添加"))
        self.pushButton_query.setText(_translate("SqliteMainWindow", "查询"))
        self.menuFile.setTitle(_translate("SqliteMainWindow", "File"))
        self.actionOpen_File.setText(_translate("SqliteMainWindow", "Open File"))

