# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addStudent.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Student(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(730, 379)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 639, 282))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.layoutWidget.sizePolicy().hasHeightForWidth())
        self.layoutWidget.setSizePolicy(sizePolicy)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lab_addTest_6 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_addTest_6.sizePolicy().hasHeightForWidth())
        self.lab_addTest_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_addTest_6.setFont(font)
        self.lab_addTest_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_addTest_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_addTest_6.setObjectName("lab_addTest_6")
        self.verticalLayout.addWidget(self.lab_addTest_6)
        self.lab_addTest = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_addTest.sizePolicy().hasHeightForWidth())
        self.lab_addTest.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_addTest.setFont(font)
        self.lab_addTest.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_addTest.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_addTest.setObjectName("lab_addTest")
        self.verticalLayout.addWidget(self.lab_addTest)
        self.lab_addTest_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_addTest_2.sizePolicy().hasHeightForWidth())
        self.lab_addTest_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_addTest_2.setFont(font)
        self.lab_addTest_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_addTest_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_addTest_2.setObjectName("lab_addTest_2")
        self.verticalLayout.addWidget(self.lab_addTest_2)
        self.lab_addTest_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_addTest_3.sizePolicy().hasHeightForWidth())
        self.lab_addTest_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_addTest_3.setFont(font)
        self.lab_addTest_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_addTest_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_addTest_3.setObjectName("lab_addTest_3")
        self.verticalLayout.addWidget(self.lab_addTest_3)
        self.lab_addTest_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lab_addTest_4.sizePolicy().hasHeightForWidth())
        self.lab_addTest_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lab_addTest_4.setFont(font)
        self.lab_addTest_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lab_addTest_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lab_addTest_4.setObjectName("lab_addTest_4")
        self.verticalLayout.addWidget(self.lab_addTest_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.SelectClass = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SelectClass.sizePolicy().hasHeightForWidth())
        self.SelectClass.setSizePolicy(sizePolicy)
        self.SelectClass.setObjectName("SelectClass")
        self.verticalLayout_2.addWidget(self.SelectClass)
        self.line_addLabel = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_addLabel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_addLabel.sizePolicy().hasHeightForWidth())
        self.line_addLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_addLabel.setFont(font)
        self.line_addLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_addLabel.setObjectName("line_addLabel")
        self.verticalLayout_2.addWidget(self.line_addLabel)
        self.line_addName = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_addName.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_addName.sizePolicy().hasHeightForWidth())
        self.line_addName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_addName.setFont(font)
        self.line_addName.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_addName.setObjectName("line_addName")
        self.verticalLayout_2.addWidget(self.line_addName)
        self.line_addSex = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_addSex.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_addSex.sizePolicy().hasHeightForWidth())
        self.line_addSex.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_addSex.setFont(font)
        self.line_addSex.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_addSex.setObjectName("line_addSex")
        self.verticalLayout_2.addWidget(self.line_addSex)
        self.line_addId = QtWidgets.QLineEdit(self.layoutWidget)
        self.line_addId.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_addId.sizePolicy().hasHeightForWidth())
        self.line_addId.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.line_addId.setFont(font)
        self.line_addId.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_addId.setObjectName("line_addId")
        self.verticalLayout_2.addWidget(self.line_addId)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_confirm = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_confirm.sizePolicy().hasHeightForWidth())
        self.btn_confirm.setSizePolicy(sizePolicy)
        self.btn_confirm.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout_2.addWidget(self.btn_confirm)
        self.btn_refresh = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_refresh.sizePolicy().hasHeightForWidth())
        self.btn_refresh.setSizePolicy(sizePolicy)
        self.btn_refresh.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_refresh.setFont(font)
        self.btn_refresh.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout_2.addWidget(self.btn_refresh)
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel.sizePolicy().hasHeightForWidth())
        self.btn_cancel.setSizePolicy(sizePolicy)
        self.btn_cancel.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "添加新用户"))
        self.lab_addTest_6.setText(_translate("Form", "选择人脸数据表"))
        self.lab_addTest.setText(_translate("Form", "添加用户标签（姓名拼音）"))
        self.lab_addTest_2.setText(_translate("Form", "添加用户姓名"))
        self.lab_addTest_3.setText(_translate("Form", "添加用户性别"))
        self.lab_addTest_4.setText(_translate("Form", "添加用户学号"))
        self.btn_confirm.setText(_translate("Form", "确定"))
        self.btn_refresh.setText(_translate("Form", "刷新"))
        self.btn_cancel.setText(_translate("Form", "取消"))

